apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 namespace: default
spec:
 selector:
   matchLabels:
    type: nginx
 replicas: 1
 template:
   metadata:
     labels:
       type: nginx
   spec:
    containers:
    - name: container
      image: shtnfo/nginx:latest
      ports:
      - containerPort: 80